export const language_en = {
    nhap_du_lieu: 'Input Data',
    tai_file_mau: 'Template file dowload',
    nhap_du_lieu_thanh_menu: 'Input menu data',
    chon_cua_hang: 'Select locations',
    time: 'Time',
    chon_cho_so: 'select metrics',
    chon_to_chuc: 'Select Shopping Mall',
    ghi_de: 'Overwrite:',
    dang_xu_ly: ' Processing',
    da_cap_nhat: 'Update sucessfully',
    ban_ghi: 'Records ',
    ban_ghi_loi: 'Error record ',
    content_tochuc: 'Pls select your mall!',
    content_cuahang: 'Pls select your locations! ',
    content_thoigian: 'Pls select start time, end time to update data!',
    content_chiso: 'Pls select your metrics!',
    content_file: 'Pls select your files ! You should use standard template files to get the best performance!',
    content_ghide: 'Pls select the metrics which you want to orverwrite. The metrics will overwrite on old metrics with the same time!',
    popup_nhap_du_lieu: 'Input data ! Do you want to import data ? After you import the data you could not see your old data anymore?',
    bo_qua: ' Ignore',
    chap_nhan: 'Accept',
    vao: ' enter',
    va: 'and',
    chon_dia_diem: 'Select your locations',
    chon_thoi_ky: 'Select time period',
    tim_kiem_dia_diem: 'Search locations',
    bao_cao_duoc_tao: 'This report was created on',
    lam_moi_bao_cao: 'Refresh your report',
    gia_tri_trung_binh_cua_hang: 'Average',
    thoi_gian_trung_binh: 'Average time',
    thoi_gian_chenh_lech: 'Time gap',
    thoi_gian_danh_gia: 'Evaluation time',
    ap_dung: ' Apply',
    dong: 'Close',
    xuat: 'Export',
    thoi_gian: 'Time',
    xem_theo: 'view by',
    Xem_theo: 'view by',
    xem: 'View ',
    so_voi: 'compared to',
    So_voi: 'Compared to',
    lan: 'times)',
    tuong_duong: 'is',
    luc: 'at',
    gio: 'Hour',
    ngay: 'Day',
    tuan: 'Week',
    thang: 'Month',
    nam: 'Year',
    phut: 'Minute',
    mot_phan_tu_gio: 'Quarter Hour',
    nua_gio: 'Half Hour',
    ngay_lam_viec: 'Workday',
    ngay_lam_viec_cuoi_tuan: 'Workday, weekend',
    dong_cua_so: 'Close',
    gio_mo_cua: 'Open Time:',
    gioi_tinh_gender: 'Gender',
    do_tuoi_age: 'Age range',
    dia_diem_khu_vuc: 'Locations',
    thoi_ky: 'Period time',
    trong_tong_so: 'of total',
    age: 'Age range',
    nu_female: 'Female',
    nam_male: 'Male',
    khong_xac_dinh: 'Unknown',
    cau_hinh: 'Configuration',
    hieu_qua_hoat_dong: 'Analysis',
    cua_hang: 'Locations',
    xuat_bao_cao: 'Report export',
    xuat_ra_excel: 'Export to Excel',
    ngay_bay_gio: 'Real time',
    so_voi_ngay_hom_qua: 'Compared to Yesterday',
    // khach_hang_dang_mua_sam: 'Number of visitors in the mall',
    // so_luong_khach_hien_tai: 'Day accumulated visitors',
    khach_hang_dang_mua_sam: 'Available',
    so_luong_khach_hien_tai: 'Number of visitors up to now',
    // tong_khach_vao: 'Total In',
    // tong_khach_ra: 'Total Out',
    tong_khach_vao: 'Total In',
    tong_khach_ra: 'Total Out',
    cau_hoi_khao_sat: 'Survey question',
    dang_dien_ra: 'Ongoing',
    sap_dien_ra: 'Upcoming',
    ket_thuc: 'End',
    so_dong: 'Show: ',
    tim_kiem: 'Search:',
    STT: 'STT',
    ho_va_ten: 'Full name',
    dien_thoai: 'Mobile number',
    danh_gia: 'Your Feedback',
    ly_do_khong_hai_long: 'the reasons made visitors unhappy ',
    y_kien_bo_sung: 'Open comments',
    khong_co_du_lieu: 'No data',
    hien_thi_theo: 'View by:',
    phan_tram: 'Percentage',
    tong_so_danh_gia: 'total feedback',
    danh_gia_bang: 'feedback',
    muc_do_khach_hang_dat_duoc: 'the performance you got',
    khach_hang_san_sang_gioi_thieu: 'visitors are ready to introduce your service to their friends',
    danh_gia_tieu_cuc_trong_tong_so: 'number of bad feedbacks of total feedbacks',
    phan_hoi_ly_do: 'let you know their unhappy factors',
    thoi_gian_co_hieu_qua_cao: 'The time to get the best/worst performance',
    gio_tot_nhat: 'The best time : 4:00 PM',
    gio_thap_nhat: 'The worst time : 10:00 AM',
    ngay_tot_nhat: 'The best day : 15/10/2018',
    ngay_thap_nhat: 'The worst day : 25/10/2018',
    nhom_cac_diem_co_ket_qua_tot_nhat: 'The best performance ones, top down',
    nhom_cac_diem_co_ket_qua_thap_nhat: 'The worst performance ones, top down',
    ly_do_khach_hang_kem_hai_long_nhat: 'The factors make shopper unhappy',
    nhom_cac_diem_co_so_luong_danh_gia_nhieu_nhat: 'The group has the most Feedbacks',
    can_no_luc: 'Need more improvement',
    can_co_gang: 'Try more',
    tot: 'Good',
    xuat_sac: 'Excellent',
    chat_luong_dich_vu_cua_ban_da_giam_xuong_dang_ke: 'your service quality is going down significantly',
    chat_luong_dich_vu_cua_ban_da_giam_xuong: 'your service quality is going down',
    chat_luong_dich_vu_cua_ban_duoc_cai_thien: 'your service quality was impoved ! Go ahead',
    chat_luong_dich_vu_cua_ban_duoc_cai_thien_dang_ke: 'your service quality is going up significantly ! Go ahead',
    luong_khach_hang_quang_ba_hinh_anh_giam: 'your brand is going down in your visitors\' mind significantly',
    luong_khach_hang_quang_ba_hinh_anh_da_giam: 'your brand is going down in your visitors\' mind',
    // tslint:disable-next-line: max-line-length
    luong_khach_hang_quang_ba_hinh_anh_tang: 'your brand is going up in your visitors\' mind and more visitors will bring their friends to you',
    // tslint:disable-next-line: max-line-length
    luong_khach_hang_quang_ba_hinh_anh_tang_len_dang_ke: 'your brand is going up in your visitors\' mind significantly and your visitors will bring their friends to you',
    bieu_do_phan_tich: 'Analysis chart',
    nguoi_nhan: 'Recipient',
    lich: 'Schedule:',
    tat_ca: 'All:',
    to_chuc: 'Organization:',
    xu_ly: 'Process:',
    cong: 'Port',
    may_chu_thu: 'Sent email server (SMTP)',
    ban_chua_nhap_may_chu: 'You did not import infomation server',
    ban_chua_nhap_cong: 'You did not import port',
    ban_chua_nhap_nguoi_gui: 'You did not import sender name',
    ban_chua_nhap_ho_ten: 'You did not import full name',
    ban_chua_nhap_email: 'You did not import email',
    ban_chua_nhap_mat_khau: 'You did not import password',
    ten_nguoi_gui: 'Sender name',
    mat_khau: 'Password',
    luu_cau_hinh: 'save',
    kiem_tra_gui_mail: 'Check email sent',
    trang_thai: 'Status',
    lich_bang: 'Schedule',
    cap_nhat: 'Update',
    co: 'Yes',
    khong: 'No',
    nhan_bao_cao: 'Get your report by Email',
    cau_hinh_gui_mail: 'Set up to send mail automatically',
    xoa: 'Delete',
    ban_co_chac_chan_muon_xoa: 'Are you sure to delete?',
    xac_nhan_xoa: 'Are you sure to delete record? You could not restore after you delete anymore',
    gui_mail: 'Send mail',
    ban_chua_nhap_noi_dung: 'You did not import content',
    noi_dung: 'Content',
    ban_chua_nhap_tieu_de: 'You did not import title',
    tieu_de: 'Title',
    cau_hinh_se_mac_dinh: 'If you do not update new schedule the report will send by default schedule!',
    bao_cao_ngay_toolip: 'Daily report will send at 8:00 AM in nexd day!',
    bao_cao_tuan_toolip: 'Weekly report will send at 24:00 in Sunday!',
    bao_cao_thang_toolip: 'Monthly report will send at 24:00 in the last day of the month!',
    danh_sach_thiet_bi: 'List of devices',
    // top_cua_hang_mua_sam: 'Top locations which visitors arrive in your mall',
    top_cua_hang_mua_sam: 'Top locations which visitors arrive in your mall',
    tat_ca_bieu_do: 'All',
    gioi_tinh: 'Gender',
    nam_bieu_do: 'Male',
    nu_bieu_do: 'Female',
    do_tuoi_bieu_do: 'Age range:',
    so_luong: 'Quantity',
    nhom: 'Group:',
    dia_diem_bieu_do: 'Location:',
    // fba
    luot_bieu_do: ' Feedback',
    phut_bieu_do: ' minutes',
    dia_diem: 'Locations',
    dia_diem__: 'Locations',
    // tslint:disable-next-line: max-line-length
    slug_login1: 'Welcome to AMMS Analytics Platform. The first IoT technology integration platform in Vietnam to bring e-commerce style shopper analytics to brick-and-mortar retailers.',
    // tslint:disable-next-line: max-line-length
    slug_login2: 'AMMS Analytics is a pioneering solution to focus entirely on optimizing the shopper experience. AMMS Analytics is being used by Top 500 leading retail and service companies in Vietnam to increase sales and shopping experiences, improve services, and eliminate unnecessary costs..',
    mot_san_pham_login: 'A service of ',
    cau_hinh_mail_bao_cao: 'The configuration to send scheduled report by mail',
    nhom_chi_so: 'Metric group',
    nhom__: 'Group',
    dang_tai_du_lieu: 'Data dowloading...',
    dang_xu_ly_du_lieu: 'Data processing...',
    dang_tai_cau_hinh: 'Configuration processing...',
    dang_tai_thong_tin_to_chuc: 'Loading organization information...',
    dang_xuat_bao_cao: 'Exporting report...',
    dang_tai_cau_hoi: 'Loading questions...',
    // 19/09/2019
    fba_tu: 'From',
    fba_den: 'to',
    fba_dang_cap_nhat: 'Updating',
    tro_giup: 'Help',
    pho_bien: 'Popular',
    truy_cap_danh_sach: 'Go the help page',
    them_moi_tro_giup: 'Add your question',
    chua_co_bai_viet_huong_dan_nao: 'No tutorial paper',
    chua_co_tom_tat_noi_dung: 'No summary of the content',
    trong_bai_viet_nay: 'In this article.',
    truy_cap_danh_sach_tro_giup: 'Go the help page',
    xoa_tat_ca: 'Delete all',
    chi_tiet_thong_bao: 'Details notification',
    thong_bao: 'notification',
    chua_co_thong_bao: 'No new notification',
    gui: 'Send',
    thay_doi_mat_khau: 'Change your password',
    mat_khau_hien_tai: 'Current Password',
    mat_khau_moi: 'New Password',
    tuy_chon_: '(option)',
    hinh_anh: 'Image',
    gui_phan_hoi: 'Send your feedback',
    dang_xuat: 'Logout',
    ten_nguoi_dung: 'Username: ',
    khong_to_chuc: 'No organization',
    thong_bao_: 'Notification: ',
    bao_cao: 'Report & Analysis ',
    // help
    trang_chu: 'Home',
    them_moi: 'Add new',
    mo_ta_chung: 'General description',
    duoi45_tu: '(less than 450 words)',
    so_tu_hien_tai_: 'Current word counts:',
    noi_dung_hien_tai: 'Current content',
    gan_the: 'Tag',
    them_gan_the: 'Add tag',
    quay_lai: 'Back',
    chi_tiet_cau_hoi_va_tro_giup: 'Detailed questions and answers',
    khong_tim_thay_bai_viet: 'Nothing Found. Apologies, but no results were found. Perhaps searching will help find a related post.',
    tac_gia_bai_viet_: 'Author: ',
    ngay_cap_nhat_: 'Updated date: ',
    trang_thai_: 'Status: ',
    luot_xem_: 'Views: ',
    chia_se: 'Shares',
    the_tag: 'Tags',
    the_tag_so: 'The tag',
    sua_thong_tin: 'Edit the info',
    sua_thong_tin_tro_giup: 'Edit help info',
    cau_hoi_va_tro_giup: 'Questions and Answers',
    ket_qua_loc_theo_: 'Results Filtered by: ',
    _tat_ca: 'All ',
    chua_co_bai_viet_tro_giup: 'Nothing Found. Apologies, but no results were found. Perhaps searching will help find a related post.',
    // admin fba
    bang_setting: 'Setting table',
    man_hinh_logo: 'ACS Smileys logo',
    man_hinh_ly_do: 'Set up the Reason visitor unhappy',
    man_hinh_thong_tin_khach_hang: 'Set up visitor information',
    man_hinh_ket_thuc: 'Set up end screen',
    so_thu_tu: 'No.',
    logo_cong_ty: 'Your logo',
    logo_ung_dung: 'Application logo',
    them_moi_thanh_cong: 'Added successfully',
    loi_xu_ly_server: 'Error server',
    ban_da_xoa_thanh_cong: 'Deleted successfully',
    co_loi_xay_ra: 'An error occurred',
    ban_chua_chon_anh_logo_ung_dung: 'You should select the application logo',
    ban_chua_chon_anh_logo_cong_ty: 'You should select your company logo',
    tiep_theo: 'Next',
    tieu_de_send: 'Title of the Send button',
    tieu_de_cancel: 'Title the Cancel button ',
    tieu_de_khung_ly_do: 'Titel of the reason frame',
    tieu_de_ly_do: 'Reason title',
    tieu_de_goi_y: 'Suggested title',
    ban_chua_nhap_tieu_de_nut_gui: 'You should add the title of the Send button',
    ban_chua_nhap_tieu_de_nut_cancel: 'You should add the title of the Cancel button',
    ban_chua_nhap_khung_ly_do: 'You should add the title of the reasoning frame',
    ban_chua_nhap_goi_y_ly_do: 'You should add the Open comments',
    ban_chua_nhap_tieu_de_ly_do: 'You should add the title of reasons',
    tieu_de_thong_tin_khach_hang: 'Customer information title',
    ban_chua_nhap_tieu_de_thong_tin_khach_hang: 'You should add the title of the customer information',
    tieu_de_khung_ten_kh: 'Customer name title',
    ban_chua_nhap_tieu_de_khung_ten_kh: 'You should add the frame title of the customer name',
    tieu_de_khung_email_kh: 'The title of customer email box',
    ban_chua_nhap_tieu_de_khung_email_kh: 'You should add the title of customer email box',
    tieu_de_khung_sdt_kh: 'The title of Customer\'s phone box',
    ban_chua_nhap_tieu_de_khung_sdt_kh: 'You should add The title of Customer\'s phone box',
    yeu_cau_tu_chon: 'Option requirements',
    yeu_cau_ten_khach_hang: ' Request of Customer\'s name',
    yeu_cau_email_khach_hang: 'Request of Customer\'s email',
    yeu_cau_sdt_khach_hang: 'Request of customer\'s phone',
    thong_diep_ket_thuc: 'The end message',
    ban_chua_nhap_thong_diep_ket_thuc: 'You should add The end message',
    xac_nhan: 'Confirm',
    sua_thong_tin_thanh_cong: 'Edited information successfully',
    // default fba
    xin_cam_on: 'Thank you!',
    hen_gap_lai_quy_khach: 'See you later',
    so_dien_thoai: 'Phone number',
    ho_ten: 'Full name',
    vui_long_cung_cap_thong_tin: 'Pls provide more information!',
    ly_do_quy_vi_hai_long: 'Pls say what make you unhappy',
    moi_nhap_ly_do: 'Please input your reasons!',
    ban_muon_gop_y_them: 'Do you have any other sugguestions for us?',
    cancel: 'Cancel',
    mac_dinh: 'Default',
    them_cau_hoi: 'Add questions',
    ten_to_chuc: 'Organization',
    tinh_trang_to_chuc: 'Question status',
    trang_thai_cau_hoi: 'Question status',
    danh_sach_cau_hoi: 'Question list',
    chien_dich: 'Campaign',
    ten_cau_hoi: 'Question name',
    thoi_gian_bat_dau: 'Start time',
    thoi_gian_ket_thuc: 'End time',
    xu_ly_: 'Process',
    bat: 'On',
    tat: 'Off',
    ban_co_chac_chan_khoi_phuc: 'Are you sure to restore?',
    xac_nhan_khoi_phuc: 'Restore confirmation',
    khoi_phuc: 'Restore',
    cau_hoi: 'Question',
    ly_do: 'Reason',
    ly_do_khac: 'Other reason',
    ban_chua_chon_to_chuc: 'You should select an organization',
    chon_cau_hoi: 'Choose a question',
    vui_long_chon_cau_hoi: '--Please select a question--',
    ban_chua_nhap_cau_hoi: 'You should add your question',
    ban_chua_nhap_chien_dich: 'You should add your campaign',
    kich_hoat: 'Actived',
    nhan: 'Label',
    chat_luong_cau_hoi: 'Question on quality',
    man_hinh_chinh: 'Home screen',
    thong_tin_khach_hang: 'Customer information',
    xin_cam_on_: 'Thank you',
    anh_ly_do: 'Photos of reasons',
    ten_ly_do: 'Name of reasons',
    nhap_ly_do_: 'Add a reason...',
    cap_nhat_cau_hoi: 'Update your question',
    mot_thiet_bi: 'A device',
    thiet_bi: 'The device ',
    vua_cam_sac: '  plugged in',
    thay_doi_ket_noi: 'change connection',
    da_tat: 'turned off',
    giam_sat_thiet_bi: 'Monitor device',
    ten_thiet_bi: 'Device name',
    vi_tri: 'Location',
    dung_luong_trong: 'Free space ',
    pin: 'Battery ',
    nguon: 'Power',
    mang: 'Network',
    dang_online: 'Online',
    them_thiet_bi: 'Add device',
    cap_nhat_thiet_bi: 'Device update',
    ban_chua_nhap_serial_number: 'You should add serial number',
    ban_chua_chon_vi_tri: 'You should select a location',
    dieu_kien_gui_thong_bao: 'Conditions to send notices',
    bang: 'Table',
    thong_tin_cau_hinh: 'Configuration information',
    phan_tram_: 'percent',
    thoi_gian_gui_thong_bao: 'Time to send notice',
    gio_: 'hours',
    them_cau_hinh: 'Add configuration',
    sua_cau_hinh: 'Edit configuration',
    chi_so_dat_dieu_kien_gui: 'KPI qualified to send notice',
    ban_chua_nhap_chi_so: 'You should add KPI to send notifications',
    khoang_thoi_gian_xu_ly: 'Time interval for processing',
    don_vi_tieng: 'hours',
    mo_hinh_boston: 'Boston matrix Report ',
    nhap_du_lieu_thanh_cong: 'Data added successful',
    file_khong_dung_dinh_dang: 'The file is not the right format',
    vui_long_chon_cua_hang: 'Please select the right locations!',
    qua_trinh_nhap_du_lieu: 'This process will overwrite your data. \n Are you sure you still want to finish this process? ',
    vui_long_chon_file: 'Please select a file!',
    qua_trinh_export: 'The file export process has failed. Please try again!',
    tat_ca_: 'All',
    anh_kich_thuoc: 'Photo size does not exceed',
    phan_hoi: 'Feedback',
    huong_dan_su_dung: 'User manual',
    khong_the_ket_noi: 'Unable to connect to the server',
    vui_long: 'Please',
    bam_vao_day: 'click here',
    de_tai_lai: 'to reload!',
    Thong_bao: 'Notification!',
    Tai_lai: 'Reload',
    Co_loi_xay_ra_Vui_long_nhan: 'An error occurred! Please click',
    Bao_cao_khach_hang_ngay: 'Traffic Report - ',
    Bao_cao_khach_hang_thang: 'Traffic Report - ',
    Bao_cao_khach_hang_nam: 'Traffic Report -',
    // Bao_cao_khach_hang_theo_loi_vao: 'Traffic Report by Zones, Entrances',
    Bao_cao_khach_hang_theo_loi_vao: 'Traffic Report by Places',
    // Ban_do_nhiet_heatmap: ' Heatmap',
    Ban_do_nhiet_heatmap: 'Heatmap',
    // Crescent Mall
    Subtotal: 'Subtotal',
    ToTal: 'Total',
    In: 'In',
    Out: 'Out',
    Average_of_In_and_Out: 'Average of In and Out',
    Rank_of_In_and_Out: 'Rank of In and Out',
    // Number_of_eletric_counter: 'Locations',
    Number_of_eletric_counter: 'CODE',
    Time: 'Time',
    FLOOR: 'SITE',
    // FLOOR: 'FLOOR',
    Daily: 'Date',
    Month: 'Month',
    dang_nhap: 'Login',
    quen_mat_khau: 'Forgot password?',
    vui_long_nhap_email: 'Please input your email!',
    quay_lai_dang_nhap: 'Back to login!',
    dang_nhap_vao_tai_khoan_cua_ban: 'Sign in to your account',
    VND: 'VND',
    Percent: ' Percent (%)',
    min: ' (min)',
    Compared: ' compared',
    Chenh_lech: ' Difference',
    To_chuc_chua_duoc_cau_hinh_email_mac_dinh: 'Organization has not had a default email configuration',
    Cap_nhat_thanh_cong: 'Successfully updated',
    Da_co_loi_xay_ra: 'An error has occurred',
    Khong_the_ket_noi_may_chu: 'Can not connect to server',
    Vui_long_thu_lai: 'Please try again',
    Du_lieu_khong_phu_hop: 'Data mismatch',
    Du_lieu_khong_thay_doi: 'Data does not change',
};
