// Thay đổi trường


export const indexes = {
  passerby: 'PasserBy',
  visitors: 'Visitors',
  shoppers: 'Shoppers',
  turn_in_rate: 'Turn in rate (%)',
  kids_visitors: 'Kids visits ',
  avg_time: 'Avg Time',
  traffic_flow: 'Traffic Flow',
  conversion_rate: 'Conversion rate (%)',
  atv: 'ATV',
  avg_items: 'Avg Items',
  sales_yield: 'Sales Yield',
  transactions: 'Transactions',
  sales: 'Sales',
  missed_sales_opportunity: 'Missed Sales Opportunity',
  sales_hours: 'Sales hours',
  shoppers_on_sales_hour: 'Shoppers on sales hour',
  sales_on_sales_hour: 'Sales on sales hour',
  member_visitors: 'Member visits (%)',
  member_transactions: 'Member transactions (%)',
  member_conversion_rate: 'Member CR (%)',
  missed_member_rate: 'Lost member CR (%)',
  gender_age: 'Gender Age',
  cx_index: 'CX Index (%)',
  nps_index: 'NPS Index (%)',
  people: 'Traffic',
  VND: 'VND',
  Percent: ' Percent (%)',
  min: ' (min)',
  Exits: ' Exits',
  Visitors: ' Visitors',
  Traffic: ' Traffic Flow',
};
export const language_index_vn = {
  people: 'Lượt đếm',
  VND: 'VNĐ',
  Percent: ' Phần trăm (%)',
  min: ' (phút)',
  Compared: ' được so sánh',
  Visitors: 'Khách vào',
  Exits: 'Khách ra',
  Traffic: 'Tổng vào ra',
};
